const providelMapping = [
    {
        chutes: "FLUX.1-schnell",
        cloudflare: "@cf/black-forest-labs/flux-1-schnell",
        deepinfra: "black-forest-labs/FLUX-1-schnell",
        fal: "fal-ai/flux-1/schnell",
        huggingface: "black-forest-labs/FLUX.1-schnell",
        imagerouter: "black-forest-labs/FLUX-1-schnell",
        nanogpt: "flux-schnell",
        replicate: "black-forest-labs/flux-schnell",
        runware: "runware:100@1",
        wavespeed: "wavespeed-ai/flux-schnell",
    },
    {
        huggingface: "black-forest-labs/FLUX.1-Kontext-dev",
        replicate: "black-forest-labs/flux-kontext-dev",
        imagerouter: "black-forest-labs/flux-kontext-dev",
        runware: "runware:106@1",
        fal: "fal-ai/flux-kontext/dev",
        nanogpt: "runware:106@1",
        wavespeed: "wavespeed-ai/flux-kontext-dev",
    },
    {
        deepinfra: "black-forest-labs/FLUX-1.1-pro",
        imagerouter: "black-forest-labs/FLUX-1.1-pro",
        runware: "bfl:2@1",
        fal: "fal-ai/flux-pro/v1.1",
        nanogpt: "flux-pro/v1.1",
        wavespeed: "wavespeed-ai/flux-1.1-pro",
    },
    {
        imagerouter: "black-forest-labs/flux-1.1-pro-ultra",
        replicate: "black-forest-labs/flux-1.1-pro-ultra",
        runware: "bfl:2@2",
        fal: "fal-ai/flux-pro/v1.1-ultra",
        nanogpt: "flux-pro/v1.1-ultra",
        wavespeed: "wavespeed-ai/flux-1.1-pro-ultra",
    },
    {
        cloudflare: "@cf/black-forest-labs/flux-2-dev",
        imagerouter: "black-forest-labs/FLUX-2-dev",
        runware: "runware:400@1",
        fal: "fal-ai/flux-2",
        wavespeed: "wavespeed-ai/flux-2-dev/text-to-image",
    },
    {
        imagerouter: "black-forest-labs/FLUX-2-flex",
        runware: "bfl:6@1",
        fal: "fal-ai/flux-2-flex",
        wavespeed: "wavespeed-ai/flux-2-flex/text-to-image",
    },
    {
        imagerouter: "black-forest-labs/FLUX-2-pro",
        runware: "bfl:5@1",
        fal: "fal-ai/flux-2-pro",
        wavespeed: "wavespeed-ai/flux-2-pro/text-to-image",
    },
    {
        imagerouter: "black-forest-labs/FLUX-2-max",
        runware: "bfl:7@1",
        fal: "fal-ai/flux-2-max",
        wavespeed: "wavespeed-ai/flux-2-max/text-to-image",
        replicate: "black-forest-labs/flux-2-max",
    },
    {
        imagerouter: "black-forest-labs/flux-kontext-max",
        runware: "bfl:4@1",
        fal: "fal-ai/flux-pro/kontext/max",
        wavespeed: "wavespeed-ai/flux-kontext-max/text-to-image",
    },
    {
        imagerouter: "black-forest-labs/flux-kontext-pro",
        runware: "bfl:3@1",
        fal: "fal-ai/flux-pro/kontext",
        nanogpt: "flux-kontext",
        wavespeed: "wavespeed-ai/flux-kontext-pro/text-to-image",
    },
    {
        deepinfra: "black-forest-labs/FLUX-pro",
        imagerouter: "black-forest-labs/FLUX-pro",
        nanogpt: "flux-pro",
    },
    {
        huggingface: "black-forest-labs/FLUX.1-dev",
        replicate: "black-forest-labs/flux-dev",
        imagerouter: "black-forest-labs/FLUX-1-dev",
        runware: "runware:101@1",
        fal: "fal-ai/flux-1/dev",
        wavespeed: "wavespeed-ai/flux-dev",
    },
    {
        huggingface: "black-forest-labs/FLUX.1-Krea-dev",
        replicate: "black-forest-labs/flux-krea-dev",
        runware: "runware:107@1",
        imagerouter: "black-forest-labs/flux-krea-dev",
        nanogpt: "runware:107@1",
        wavespeed: "wavespeed-ai/flux-krea-dev-lora",
    },
    {
        cloudflare: "@cf/bytedance/stable-diffusion-xl-lightning",
        huggingface: "ByteDance/SDXL-Lightning",
        replicate: "bytedance/sdxl-lightning-4step",
        fal: "fal-ai/fast-lightning-sdxl",
    },
    {
        huggingface: "ByteDance/Hyper-SD",
        replicate: "bytedance/hyper-flux-16step",
    },
    {
        huggingface: "playgroundai/playground-v2.5-1024px-aesthetic",
        replicate: "playgroundai/playground-v2.5-1024px-aesthetic:a45f82a1382bed5c7aeb861dac7c7d191b0fdf74d8d57c4a0e6ed7d4d0bf7d24",
        fal: "fal-ai/playground-v25",
        nanogpt: "playground-v25",
    },
    {
        huggingface: "Qwen/Qwen-Image",
        replicate: "qwen/qwen-image",
        fal: "fal-ai/qwen-image",
        imagerouter: "qwen/qwen-image",
        runware: "runware:108@1",
        chutes: "qwen-image",
        wavespeed: "wavespeed-ai/qwen-image/text-to-image",
        nanogpt: "qwen-image",
    },
    {
        huggingface: "Qwen/Qwen-Image-Edit",
        replicate: "qwen/qwen-image-edit",
        imagerouter: "qwen/qwen-image-edit",
        runware: "runware:108@20",
        fal: "fal-ai/qwen-image-edit",
        wavespeed: "wavespeed-ai/qwen-image/edit",
        nanogpt: "qwen-image",
    },
    {
        imagerouter: "qwen/qwen-image-edit-plus",
        runware: "runware:108@22",
        fal: "fal-ai/qwen-image-edit-plus",
    },
    {
        huggingface: "stabilityai/stable-diffusion-3-medium",
        replicate: "stability-ai/stable-diffusion-3",
        fal: "fal-ai/stable-diffusion-v3-medium",
        imagerouter: "stabilityai/sd3",
        runware: "runware:5@1",
        wavespeed: "stability-ai/stable-diffusion-3",
    },
    {
        huggingface: "stabilityai/stable-diffusion-3.5-medium",
        replicate: "stability-ai/stable-diffusion-3.5-medium",
        fal: "fal-ai/stable-diffusion-v35-medium",
        wavespeed: "stability-ai/stable-diffusion-3.5-medium",
    },
    {
        huggingface: "stabilityai/stable-diffusion-3.5-large",
        replicate: "stability-ai/stable-diffusion-3.5-large",
        imagerouter: "stabilityai/sd3.5",
        replicate: "stability-ai/stable-diffusion-3.5-large",
        fal: "fal-ai/stable-diffusion-v35-large",
        nanogpt: "stable-diffusion-v35-large",
        wavespeed: "stability-ai/stable-diffusion-3.5-large",
    },
    {
        huggingface: "stabilityai/stable-diffusion-3.5-large-turbo",
        replicate: "stability-ai/stable-diffusion-3.5-large-turbo",
        wavespeed: "stability-ai/stable-diffusion-3.5-large-turbo",
    },
    {
        imagerouter: "stabilityai/sdxl",
        cloudflare: "@cf/stabilityai/stable-diffusion-xl-base-1.0",
        huggingface: "stabilityai/stable-diffusion-xl-base-1.0",
        replicate: "stability-ai/sdxl:7762fd07cf82c948538e41f63f77d685e02b063e37e496e96eefd46c929f9bdc",
        chutes: "stabilityai/stable-diffusion-xl-base-1.0",
        wavespeed: "stability-ai/sdxl",
        runware: "civitai:101055@128078",
    },
    {
        huggingface: "tencent/HunyuanImage-2.1",
        replicate: "tencent/hunyuan-image-2.1",
        fal: "fal-ai/hunyuan-image/v2.1/text-to-image",
        wavespeed: "wavespeed-ai/hunyuan-image-2.1",
    },
    {
        huggingface: "tencent/HunyuanImage-3.0",
        replicate: "tencent/hunyuan-image-3",
        imagerouter: "tencent/hunyuan-image-3",
        nanogpt: "hunyuan-image-3",
        fal: "fal-ai/hunyuan-image/v3/text-to-image",
        chutes: "hunyuan-image-3",
        wavespeed: "wavespeed-ai/hunyuan-image-3",
    },
    {
        huggingface: "zeke/rider-waite-tarot-flux",
        replicate: "tarot-cards/rider-waite:6d77a07ef88e8a09389385cb14d98b12629a4b23b0537b01dfeb833c32827546",
    },
    {
        huggingface: "Wan-AI/Wan2.1-T2V-14B",
        replicate: "wavespeedai/wan-2.1-t2v-480p",
    },
    {
        huggingface: "Wan-AI/Wan2.1-T2V-1.3B",
        replicate: "wan-video/wan-2.1-1.3b",
    },
    {
        huggingface: "Wan-AI/Wan2.2-T2V-A14B",
        replicate: "wan-video/wan-2.2-t2v-fast",
        fal: "fal-ai/wan/v2.2-5b/text-to-video",
    },
    {
        huggingface: "Wan-AI/Wan2.2-TI2V-5B",
        replicate: "wan-video/wan-2.2-5b-fast",
        fal: "fal-ai/wan/v2.2-5b",
    },
    {
        huggingface: "Wan-AI/Wan2.2-T2V-A14B-Diffusers",
        replicate: "wan-video/wan-2.2-t2v-fast",
    },
    {
        huggingface: "Wan-AI/Wan2.2-I2V-A14B",
        replicate: "wan-video/wan-2.2-i2v-fast",
        fal: "fal-ai/wan-i2v",
    },
    {
        huggingface: "Lightricks/LTX-Video",
        replicate: "lightricks/ltx-video",
        fal: "fal-ai/ltx-video",
    },
    {
        huggingface: "hexgrad/Kokoro-82M",
        replicate: "jaaari/kokoro-82m:f559560eb822dc509045f3921a1921234918b91739db4bf3daab2169b71c7a13",
    },
    {
        huggingface: "microsoft/Phi-4-multimodal-instruct",
        replicate: "microsoft/phi-4-multimodal-instruct:40c8f5c03ce250441855e776528bafd11cdb302c6677613acc0942c58dbd0afa",
    },
    {
        huggingface: "openai/whisper-large-v3",
        replicate: "openai/whisper:8099696689d249cf8b122d833c36ac3f75505c666a395ca40ef26f68e7d3d16e",
        fal: "fal-ai/whisper",
    },
    {
        imagerouter: "asiryan/Realistic-Vision",
        runware: "civitai:4201@130072",
        fal: "fal-ai/realistic-vision",
    },
    {
        deepinfra: "Bria/blur_background",
        imagerouter: "bria/blur-background",
    },
    {
        deepinfra: "Bria/Bria-3.2",
        imagerouter: "bria/bria-3.2",
        fal: "bria/text-to-image/3.2",
        wavespeed: "bria/text-to-image-3.2",
    },
    {
        deepinfra: "Bria/Bria-3.2-vector",
        imagerouter: "bria/bria-3.2-vector",
    },
    {
        imagerouter: "bria/bria-fibo",
        runware: "bria:20@1",
        huggingface: "briaai/FIBO",
        replicate: "bria/fibo",
        fal: "bria/fibo/generate",
        wavespeed: "bria/fibo",
    },
    {
        deepinfra: "Bria/enhance",
        imagerouter: "bria/enhance",
    },
    {
        deepinfra: "Bria/erase_foreground",
        imagerouter: "bria/erase-foreground",
        fal: "fal-ai/bria/eraser",
        wavespeed: "bria/eraser",
    },
    {
        deepinfra: "Bria/remove_background",
        imagerouter: "bria/remove-background",
        runware: "runware:110@1",
        fal: "fal-ai/bria/background/remove",
        wavespeed: "bria/remove-background",
    },
    {
        fal: "fal-ai/bytedance/dreamina/v3.1/text-to-image",
        imagerouter: "bytedance/dreamina-3.1",
        wavespeed: "bytedance/dreamina-v3.1/text-to-image",
    },
    {
        chutes: "infiniteyou",
        imagerouter: "ByteDance/InfiniteYou",
    },
    {
        imagerouter: "bytedance/seedance-1-lite",
        runware: "bytedance:1@1",
        wavespeed: "bytedance/seedance-v1-lite-t2v-720p",
        fal: "fal-ai/bytedance/seedance/v1/lite/text-to-video",
    },
    {
        imagerouter: "bytedance/seedance-1-pro",
        runware: "bytedance:2@1",
        wavespeed: "bytedance/seedance-v1-pro-t2v-720p",
        fal: "fal-ai/bytedance/seedance/v1/pro/text-to-video",
    },
    {
        imagerouter: "bytedance/seedance-1-pro-fast",
        runware: "bytedance:2@2",
        fal: "fal-ai/bytedance/seedance/v1/pro/fast/text-to-video",
    },
    {
        fal: "fal-ai/bytedance/seededit/v3/edit-image",
        imagerouter: "bytedance/seededit-3",
        runware: "bytedance:4@1",
        wavespeed: "bytedance/seededit-v3",
    },
    {
        fal: "fal-ai/bytedance/seedream/v3/text-to-image",
        imagerouter: "bytedance/seedream-3",
        nanogpt: "seedream-v3",
        runware: "bytedance:3@1",
        wavespeed: "bytedance/seedream-v3",
    },
    {
        imagerouter: "bytedance/seedream-4",
        nanogpt: "seedream-v4",
        runware: "bytedance:5@0",
        deepinfra: "ByteDance/Seedream-4",
        fal: "fal-ai/bytedance/seedream/v4/text-to-image",
        replicate: "bytedance/seedream-4",
        wavespeed: "bytedance/seedream-v4",
        
    },
    {
        imagerouter: "cagliostrolab/animagine-xl-3.0",
        runware: "civitai:260267@293564",
    },
    {
        imagerouter: "csslc/ccsr-2x",
        runware: "runware:501@1",
        fal: "fal-ai/ccsr",
    },
    {
        imagerouter: "cyberdelia/CyberRealisticPony",
        runware: "pasaranax:443821@1957537",
    },
    {
        gemini: "gemini-2.5-flash-image",
        imagerouter: "google/gemini-2.5-flash",
        vertex: "gemini-2.5-flash-image",
        fal: "fal-ai/gemini-25-flash-image",
        nanogpt: "google:4@1",
        runware: "google:4@1",
        replicate: "google/gemini-2.5-flash-image",
        wavespeed: "google/gemini-2.5-flash-image/text-to-image",
    },
    {
        gemini: "gemini-3-pro-image-preview",
        imagerouter: "google/gemini-3-pro",
        fal: "fal-ai/gemini-3-pro-image-preview",
        nanogpt: "nano-banana-pro",
        runware: "google:4@2",
        wavespeed: "google/gemini-3-pro-image/text-to-image",
    },
    {
        geminiImagen: "imagen-3.0-generate-002",
        imagerouter: "google/imagen-3",
        vertex: "imagen-3.0-generate-002",
        fal: "fal-ai/imagen3",
        wavespeed: "google/imagen3",
    },
    {
        imagerouter: "google/imagen-3-fast",
        vertex: "imagen-3.0-fast-generate-001",
        fal: "fal-ai/imagen3/fast",
        wavespeed: "google/imagen3-fast",
    },
    {
        imagerouter: "google/imagen-4",
        vertex: "imagen-4.0-generate-001",
        fal: "fal-ai/imagen4/preview",
        nanogpt: "imagen-4",
        wavespeed: "google/imagen4",
    },
    {
        imagerouter: "google/imagen-4-05-20",
        vertex: "imagen-4.0-generate-preview-05-20",
    },
    {
        imagerouter: "google/imagen-4-06-06",
        vertex: "imagen-4.0-generate-preview-06-06",
    },
    {
        imagerouter: "google/imagen-4-fast",
        vertex: "imagen-4.0-fast-generate-001",
        fal: "fal-ai/imagen4/preview/fast",
        nanogpt: "imagen-4-fast",
        wavespeed: "google/imagen4-fast",
    },
    {
        imagerouter: "google/imagen-4-fast-06-06",
        vertex: "imagen-4.0-fast-generate-preview-06-06",
    },
    {
        imagerouter: "google/imagen-4-ultra",
        vertex: "imagen-4.0-ultra-generate-001",
        fal: "fal-ai/imagen4/preview/ultra",
        nanogpt: "imagen-4-ultra",
    },
    {
        imagerouter: "google/imagen-4-ultra-05-20",
        vertex: "imagen-4.0-ultra-generate-exp-05-20",
    },
    {
        imagerouter: "google/imagen-4-ultra-06-06",
        vertex: "imagen-4.0-ultra-generate-preview-06-06",
    },
    {
        gemini: "veo-2.0-generate-001",
        imagerouter: "google/veo-2",
        fal: "fal-ai/veo2/image-to-video",
        wavespeed: "google/veo2",
    },
    {
        gemini: "veo-3.0-generate-001",
        imagerouter: "google/veo-3",
        fal: "fal-ai/veo3",
        wavespeed: "google/veo3",
    },
    {
        gemini: "veo-3.0-fast-generate-001",
        imagerouter: "google/veo-3-fast",
        fal: "fal-ai/veo3/fast",
        wavespeed: "google/veo3-fast",
    },
    {
        gemini: "veo-3.1-generate-preview",
        imagerouter: "google/veo-3.1",
        fal: "fal-ai/veo3.1",
        replicate: "google/veo-3.1",
        wavespeed: "google/veo3.1/text-to-video",
    },
    {
        replicate: "google/veo-3.1-fast",
        fal: "fal-ai/veo3.1/fast",
        gemini: "veo-3.1-fast-generate-preview",
        imagerouter: "google/veo-3.1-fast",
        wavespeed: "google/veo3.1-fast/text-to-video",
    },
    {
        fal: "fal-ai/hidream-e1-1",
        imagerouter: "HiDream-ai/HiDream-E1-1",
        nanogpt: "hidream-e1-1",
        wavespeed: "wavespeed-ai/hidream-e1-full",
    },
    {
        imagerouter: "HiDream-ai/HiDream-I1-Dev",
        runware: "runware:97@2",
        fal: "fal-ai/hidream-i1-dev",
    },
    {
        imagerouter: "HiDream-ai/HiDream-I1-Fast",
        runware: "runware:97@3",
        fal: "fal-ai/hidream-i1-fast",
        nanogpt: "hidream-i1-fast",
    },
    {
        imagerouter: "HiDream-ai/HiDream-I1-Full",
        runware: "runware:97@1",
        chutes: "hidream",
        fal: "fal-ai/hidream-i1-full",
        nanogpt: "hidream",
        wavespeed: "wavespeed-ai/hidream-i1-full",
    },
    {
        imagerouter: "ideogram-ai/ideogram-v2a",
        replicate: "ideogram-ai/ideogram-v2a",
        fal: "fal-ai/ideogram/v2a",
        wavespeed: "ideogram-ai/ideogram-v2a",
    },
    {
        imagerouter: "ideogram-ai/ideogram-v2a-turbo",
        replicate: "ideogram-ai/ideogram-v2a-turbo",
        fal: "fal-ai/ideogram/v2a/turbo",
        wavespeed: "ideogram-ai/ideogram-v2-turbo",
    },
    {
        imagerouter: "ideogram-ai/ideogram-v3",
        replicate: "ideogram-ai/ideogram-v3",
        fal: "fal-ai/ideogram/v3",
        nanogpt: "ideogram-v3-default",
    },
    {
        imagerouter: "ideogram-ai/ideogram-v3-balanced",
        replicate: "ideogram-ai/ideogram-v3-balanced",
        wavespeed: "ideogram-ai/ideogram-v3-balanced",
    },
    {
        imagerouter: "ideogram-ai/ideogram-v3-quality",
        replicate: "ideogram-ai/ideogram-v3-quality",
        nanogpt: "ideogram-v3-quality",
        wavespeed: "ideogram-ai/ideogram-v3-quality",
    },
    {
        imagerouter: "ideogram-ai/ideogram-v3-turbo",
        replicate: "ideogram-ai/ideogram-v3-turbo",
        nanogpt: "ideogram-v3-turbo",
        wavespeed: "ideogram-ai/ideogram-v3-turbo",
    },
    {
        imagerouter: "imagineart/imagineart-1.5",
        runware: "imagineart:1@5",
        fal: "imagineart/imagineart-1.5-preview/text-to-image",
    },
    {
        imagerouter: "jingyunliang/swinir-2x",
        runware: "runware:503@1",
    },
    {
        imagerouter: "kwaivgi/kling-1.6-standard",
        replicate: "kwaivgi/kling-v1.6-standard",
        runware: "klingai:3@1",
        fal: "fal-ai/kling-video/v1.6/pro/image-to-video",
    },
    {
        imagerouter: "kwaivgi/kling-2.1-master",
        replicate: "kwaivgi/kling-v2.1-master",
        runware: "klingai:4@3",
        fal: "fal-ai/kling-video/v2.1/master/image-to-video",
    },
    {
        imagerouter: "kwaivgi/kling-2.1-pro",
        replicate: "kwaivgi/kling-v2.1",
        runware: "klingai:5@2",
        fal: "fal-ai/kling-video/v2.1/pro/image-to-video",
        wavespeed: "kwaivgi/kling-v2.1-i2v-pro",
    },
    {
        imagerouter: "kwaivgi/kling-2.1-standard",
        replicate: "kwaivgi/kling-v2.1",
        runware: "klingai:5@1",
        fal: "fal-ai/kling-video/v2.1/standard/image-to-video",
        wavespeed: "kwaivgi/kling-v2.1-i2v-standard",
    },
    {
        imagerouter: "kwaivgi/kling-2.5-turbo-pro",
        runware: "klingai:6@1",
        fal: "fal-ai/kling-video/v2.5-turbo/pro/image-to-video",
        wavespeed: "kwaivgi/kling-v2.5-turbo-pro/text-to-video",
    },
    {
        imagerouter: "kwaivgi/kling-2.5-turbo-standard",
        runware: "klingai:6@0",
        fal: "fal-ai/kling-video/v2.5-turbo/standard/image-to-video",
        wavespeed: "kwaivgi/kling-v2.5-turbo-std/image-to-video",
    },
    {
        imagerouter: "kwaivgi/wan-2.2",
        runware: "runware:200@6",
        wavespeed: "wavespeed-ai/wan-2.2/t2v-720p",
    },
    {
        imagerouter: "kwaivgi/wan-2.5",
        runware: "runware:201@1",
        fal: "fal-ai/wan-25-preview/image-to-video",
        wavespeed: "alibaba/wan-2.5/text-to-video",
    },
    {
        cloudflare: "@cf/leonardo/lucid-origin",
        imagerouter: "leonardoai/lucid-origin",
        nanogpt: "lucid-origin",
        replicate: "leonardoai/lucid-origin",
        wavespeed: "leonardoai/lucid-origin",
    },
    {
        imagerouter: "lightricks/ltx-2-fast",
        runware: "lightricks:2@1",
        fal: "fal-ai/ltx-2/text-to-video/fast",
        wavespeed: "lightricks/ltx-2-fast/text-to-video",
    },
    {
        imagerouter: "lightricks/ltx-2-pro",
        runware: "lightricks:2@0",
        fal: "fal-ai/ltx-2/text-to-video",
        wavespeed: "lightricks/ltx-2-pro/text-to-video",
    },
    {
        chutes: "chroma",
        imagerouter: "lodestones/Chroma",
        nanogpt: "chroma",
        wavespeed: "wavespeed-ai/chroma",
    },
    {
        imagerouter: "luma/photon",
        replicate: "luma/photon",
        fal: "fal-ai/luma-photon",
        wavespeed: "luma/photon",
    },
    {
        imagerouter: "luma/photon-flash",
        replicate: "luma/photon-flash",
        fal: "fal-ai/luma-photon/flash",
        wavespeed: "luma/photon-flash",
    },
    {
        cloudflare: "@cf/lykon/dreamshaper-8-lcm",
        imagerouter: "Lykon/DreamShaper",
        runware: "civitai:4384@128713",
        chutes: "Lykon/dreamshaper-xl-1-0",
    },
    {
        cloudflare: "@cf/leonardo/phoenix-1.0",
    },
    {
        cloudflare: "@cf/runwayml/stable-diffusion-v1-5-img2img",
        fal: "fal-ai/stable-diffusion-v35-large",
    },
    {
        cloudflare: "@cf/runwayml/stable-diffusion-v1-5-inpainting",
        fal: "fal-ai/stable-diffusion-v35-large",
    },
    {
        imagerouter: "midjourney/midjourney",
        nanogpt: "midjourney",
    },
    {
        imagerouter: "minimax/hailuo-02-pro",
        wavespeed: "minimax/hailuo-02/pro",
        fal: "fal-ai/minimax/hailuo-2.3/pro/image-to-video",
    },
    {
        imagerouter: "minimax/hailuo-02-standard",
        runware: "minimax:3@1",
        wavespeed: "minimax/hailuo-02/standard",
        fal: "fal-ai/minimax/hailuo-02/standard/image-to-video",
    },
    {
        imagerouter: "minimax/hailuo-2.3",
        runware: "minimax:4@1",
        fal: "fal-ai/minimax/hailuo-2.3/standard/image-to-video",
        wavespeed: "minimax/hailuo-2.3/t2v-standard",
    },
    {
        imagerouter: "minimax/hailuo-2.3-fast",
        runware: "minimax:4@2",
        fal: "fal-ai/minimax/hailuo-2.3-fast/standard/image-to-video",
        wavespeed: "minimax/hailuo-2.3/fast",
    },
    {
        imagerouter: "minimax/image-01",
        replicate: "minimax/image-01",
        fal: "fal-ai/minimax/image-01",
    },
    {
        imagerouter: "openai/dall-e-2",
        openai: "dall-e-2",
        wavespeed: "openai/dall-e-2",
    },
    {
        imagerouter: "openai/dall-e-3",
        openai: "dall-e-3",
        wavespeed: "openai/dall-e-3",
    },
    {
        imagerouter: "openai/gpt-image-1",
        nanogpt: "gpt-image-1",
        openai: "gpt-image-1",
        fal: "fal-ai/gpt-image-1/text-to-image",
        wavespeed: "openai/gpt-image-1",
        runware: "openai:1@1",
        replicate: "openai/gpt-image-1",
    },
    {
        imagerouter: "openai/gpt-image-1-mini",
        nanogpt: "gpt-image-1-mini",
        openai: "gpt-image-1-mini",
        fal: "fal-ai/gpt-image-1-mini",
        wavespeed: "openai/gpt-image-1-mini/text-to-image",
        replicate: "openai/gpt-image-1-mini",
    },
    {
        imagerouter: "openai/gpt-image-1.5",
        nanogpt: "gpt-image-1.5",
        openai: "gpt-image-1.5",
        fal: "fal-ai/gpt-image-1.5",
        wavespeed: "openai/gpt-image-1.5/text-to-image",
        replicate: "openai/gpt-image-1.5",
        runware: "openai:4@1",
    },
    {
        imagerouter: "openai/sora-2",
        runware: "openai:3@1",
        replicate: "openai/sora-2",
        nanogpt: "sora-2",
        wavespeed: "openai/sora",
    },
    {
        imagerouter: "philz1337x/clarity-2x",
        runware: "runware:500@1",
    },
    {
        fal: "fal-ai/recraft/v3/text-to-image",
        imagerouter: "recraft-ai/recraft-v3",
        nanogpt: "recraft-v3",
        wavespeed: "recraft-ai/recraft-v3",
    },
    {
        imagerouter: "recraft-ai/recraft-v3-svg",
        replicate: "recraft-ai/recraft-v3-svg",
        wavespeed: "recraft-ai/recraft-v3-svg",
    },
    {
        fal: "fal-ai/recraft/vectorize",
        imagerouter: "recraft-ai/recraft-vectorize",
    },
    {
        imagerouter: "reve/reve-1",
        replicate: "reve/create",
        fal: "fal-ai/reve/text-to-image",
        wavespeed: "reve/text-to-image",
    },
    {
        imagerouter: "run-diffusion/Juggernaut-Flux",
        runware: "rundiffusion:120@100",
        fal: "rundiffusion-fal/juggernaut-flux/lightning",
    },
    {
        imagerouter: "run-diffusion/Juggernaut-Lightning-Flux",
        runware: "rundiffusion:110@101",
        fal: "rundiffusion-fal/juggernaut-flux/lightning",
    },
    {
        imagerouter: "run-diffusion/Juggernaut-Pro-Flux",
        runware: "rundiffusion:130@100",
        fal: "rundiffusion-fal/juggernaut-flux/pro",
    },
    {
        imagerouter: "run-diffusion/Juggernaut-XL",
        runware: "civitai:133005@782002",
        fal: "rundiffusion-fal/juggernaut-flux/lightning",
        chutes: "JuggernautXL",
    },
    {
        imagerouter: "run-diffusion/RunDiffusion-Photo-Flux",
        runware: "rundiffusion:500@100",
        fal: "rundiffusion-fal/rundiffusion-photo-flux",
    },
    {
        imagerouter: "SG161222/RealVisXL",
        runware: "civitai:139562@798204",
    },
    {
        imagerouter: "sourceful/riverflow-1",
        runware: "sourceful:1@1",
    },
    {
        imagerouter: "sourceful/riverflow-1-mini",
        runware: "sourceful:1@0",
    },
    {
        imagerouter: "stabilityai/latent-2x",
        runware: "runware:502@1",
    },
    {
        imagerouter: "stabilityai/sd1.5-dpo",
        runware: "civitai:240850@271743",
    },
    {
        huggingface: "stabilityai/sdxl-turbo",
        deepinfra: "stabilityai/sdxl-turbo",
        imagerouter: "stabilityai/sdxl-turbo",
        runware: "civitai:215418@273102",
        replicate: "jyoung105/sdxl-turbo",
    },
    {
        imagerouter: "wavespeed/ghibli",
        wavespeed: "wavespeed-ai/ghibli",
    },
    {
        grok: "grok-2-image",
        imagerouter: "xAI/grok-2-image",
        replicate: "xai/grok-2-image",
    },
    {
        huggingface: "Tongyi-MAI/Z-Image-Turbo",
        imagerouter: "Tongyi-MAI/Z-Image-Turbo",
        replicate: "prunaai/z-image-turbo",
        fal: "fal-ai/z-image/turbo",
        wavespeed: "wavespeed-ai/z-image/turbo",
        nanogpt: "z-image-turbo",
    },
    {
        fal: "fal-ai/ovis-image",
        huggingface: "AIDC-AI/Ovis-Image-7B",
        imagerouter: "AIDC-AI/Ovis-Image-7B"
    },
    {
        fal: "fal-ai/bytedance/seedream/v4.5/text-to-image",
        imagerouter: "bytedance/seedream-4.5",
        wavespeed: "bytedance/seedream-v4.5",
        nanogpt: "seedream-v4.5",
        replicate: "bytedance/seedream-4.5",
        runware: "bytedance:seedream@4.5",
    },
    {
        imagerouter: "prunaai/P-Image-1.0",
        replicate: "prunaai/p-image",
        runware: "prunaai:1@1",
    },
    {
        imagerouter: "fal/flux-2-dev-turbo",
        fal: "fal-ai/flux-2/turbo",
        huggingface: "fal/FLUX.2-dev-Turbo",
        wavespeed: "wavespeed-ai/flux-2-turbo/text-to-image",
        replicate: "prunaai/flux-2-turbo",
    },
    {
        imagerouter: "zai/glm-image",
        huggingface: "zai-org/GLM-Image",
        nanogpt: "glm-image",
        fal: "fal-ai/glm-image",
        wavespeed: "z-ai/glm-image/text-to-image",
    }
];
